version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp_data:/var/www/html
      
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    restart : always
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html

volumes:
  db_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wp_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  inception:
    driver: bridge